# Generated by Django 3.1 on 2022-07-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('top_right_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст в верхнем правом углу')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Главное изображение')),
                ('img_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание изображения')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('logo_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание логотипа')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_top_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Верхний блок',
                'verbose_name_plural': 'Верхние блоки',
            },
        ),
    ]
