# Generated by Django 3.1 on 2022-07-04 17:11

import app.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('top_text', models.TextField(blank=True, null=True, verbose_name='Верхний текст')),
                ('title_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_description_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Блок описания',
                'verbose_name_plural': 'Блоки описания',
            },
        ),
        migrations.CreateModel(
            name='FunctionalityColumnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Элемент функционала')),
            ],
            options={
                'verbose_name': 'Колонка функционала',
                'verbose_name_plural': 'Колонки функционала(Блок реализации)',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_block_problem', to='blocks.descriptionblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы(Блок описания)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_team_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Блок команды',
                'verbose_name_plural': 'Блок команды',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Верхний текст')),
                ('big_text', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Нижний текст')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_technologies_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Блок технологий',
                'verbose_name_plural': 'Блок технологий',
            },
        ),
        migrations.CreateModel(
            name='TechnologyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_technology', to='blocks.technologiesblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='TeamItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Элемент команды')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_team_member', to='blocks.teamblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент команды',
                'verbose_name_plural': 'Элементы команды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProblemPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_part', to='blocks.problem', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Часть проблемы',
                'verbose_name_plural': 'Части проблемы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Верхний подзаголовок')),
                ('subtitle_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Нижний подзаголовок')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Верхний текст')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Текст под вторым подзаголовком')),
                ('bottom_text', models.TextField(blank=True, null=True, verbose_name='Нижний текст')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_implementation_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Блок реализации',
                'verbose_name_plural': 'Блок реализации',
            },
        ),
        migrations.CreateModel(
            name='FunctionalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Элемент функционала')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('column', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_functionality', to='blocks.functionalitycolumnmodel', verbose_name='Колонка')),
            ],
            options={
                'verbose_name': 'Элемент функционала',
                'verbose_name_plural': 'Элементы функционала',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='functionalitycolumnmodel',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_column', to='blocks.implementationblockmodel', verbose_name='Блок'),
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=True, verbose_name='Оставить настройки по умолчанию')),
                ('color', app.fields.ColorField(default='#4036ba', max_length=10, verbose_name='Выбрать цвет')),
                ('description_font_color', app.fields.ColorField(default='#4036ba', max_length=10, verbose_name='Выбрать цвет текста в блоке описания')),
                ('secondary_color', app.fields.ColorField(default='#24d7ff', max_length=10, verbose_name='Выбрать второй цвет')),
                ('order', models.IntegerField(default=0, verbose_name='Применяется схема с наименьшим номером')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_block', to='cases.casepage', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BottomSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('img_alt', models.CharField(max_length=255, verbose_name='Описание изображения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_slider_image', to='blocks.implementationblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'ordering': ['order'],
            },
        ),
    ]
