# Generated by Django 3.1 on 2022-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caform', '0002_formmodel_servicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='html_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя для html формы'),
        ),
    ]
