# Generated by Django 3.1 on 2022-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0003_auto_20220612_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('header_menu', 'Верхнее меню'), ('extended_menu', 'Развёрнутое меню'), ('extended_submenu', 'Развёрнутое подменю')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
