# Generated by Django 3.1 on 2022-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('top_left_text', models.CharField(max_length=255, verbose_name='Текст в верхнем левом углу')),
                ('top_right_text', models.CharField(max_length=255, verbose_name='Текст в верхнем правом углу')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('img_alt', models.CharField(max_length=255, verbose_name='Описание изображения')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('logo_alt', models.CharField(max_length=255, verbose_name='Описание логотипа')),
            ],
            options={
                'verbose_name': 'Верхний блок',
                'verbose_name_plural': 'Верхние блоки',
            },
        ),
    ]
