# Generated by Django 3.1 on 2022-06-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_topblockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('phone_url', models.CharField(max_length=30, verbose_name='Телефон ссылка')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('logo_alt', models.CharField(max_length=255, verbose_name='Описание логотипа')),
            ],
            options={
                'verbose_name': 'Верхушка сайта',
                'verbose_name_plural': 'Верхушка сайта',
            },
        ),
        migrations.CreateModel(
            name='ImplementationBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('top_subtitle', models.CharField(max_length=255, verbose_name='Верхний подзаголовок')),
                ('bottom_subtitle', models.CharField(max_length=255, verbose_name='Нижний подзаголовок')),
                ('top_text', models.TextField(verbose_name='Верхний текст')),
                ('bottom_text', models.TextField(verbose_name='Нижний текст')),
                ('top_img', models.ImageField(upload_to='', verbose_name='Верхнее изображение')),
                ('top_img_alt', models.CharField(max_length=255, verbose_name='Описание верхнего изображения')),
                ('bottom_left_img', models.ImageField(upload_to='', verbose_name='Левое нижнее изображение')),
                ('bottom_left_img_alt', models.CharField(max_length=255, verbose_name='Описание левого нижнего изображения')),
            ],
            options={
                'verbose_name': 'Блок реализации',
                'verbose_name_plural': 'Блок реализации',
            },
        ),
        migrations.CreateModel(
            name='FunctionalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Элемент функционала')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_functionality', to='home.implementationblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент функционала',
                'verbose_name_plural': 'Элементы функционала',
            },
        ),
    ]
