# Generated by Django 3.1 on 2022-06-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220613_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('top_text', models.TextField(blank=True, null=True, verbose_name='Верхний текст')),
                ('title_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок описания',
                'verbose_name_plural': 'Блоки описания',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_block_problem', to='home.descriptionblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='ProblemPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_part', to='home.problem', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Часть проблемы',
                'verbose_name_plural': 'Части проблемы',
            },
        ),
    ]
