# Generated by Django 3.1 on 2022-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_descriptionblockmodel_problem_problempart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='headermodel',
            name='phone_url',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон ссылка'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='img_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание логотипа'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='topblockmodel',
            name='top_right_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст в верхнем правом углу'),
        ),
    ]
