# Generated by Django 3.1 on 2022-06-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220614_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalitymodel',
            name='block',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='bottom_left_img',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='bottom_left_img_alt',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='bottom_subtitle',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='top_img',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='top_img_alt',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='top_subtitle',
        ),
        migrations.RemoveField(
            model_name='implementationblockmodel',
            name='top_text',
        ),
        migrations.AddField(
            model_name='implementationblockmodel',
            name='subtitle_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Верхний подзаголовок'),
        ),
        migrations.AddField(
            model_name='implementationblockmodel',
            name='subtitle_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нижний подзаголовок'),
        ),
        migrations.AddField(
            model_name='implementationblockmodel',
            name='text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Верхний текст'),
        ),
        migrations.AddField(
            model_name='implementationblockmodel',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Нижний текст'),
        ),
        migrations.AlterField(
            model_name='implementationblockmodel',
            name='bottom_text',
            field=models.TextField(blank=True, null=True, verbose_name='Нижний текст'),
        ),
        migrations.CreateModel(
            name='FunctionalityColumnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Элемент функционала')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_column', to='home.implementationblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Колонка функционала',
                'verbose_name_plural': 'Колонки функционала',
            },
        ),
        migrations.CreateModel(
            name='BottomSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Верхнее изображение')),
                ('img_alt', models.CharField(max_length=255, verbose_name='Описание верхнего изображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_slider_image', to='home.implementationblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
            },
        ),
        migrations.AddField(
            model_name='functionalitymodel',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_functionality', to='home.functionalitycolumnmodel', verbose_name='Блок'),
        ),
    ]
