# Generated by Django 3.1 on 2022-06-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220618_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalitymodel',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_functionality', to='home.functionalitycolumnmodel', verbose_name='Колонка'),
        ),
    ]
