# Generated by Django 3.1 on 2022-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220618_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomslide',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bottomslide',
            name='img_alt',
            field=models.CharField(max_length=255, verbose_name='Описание изображения'),
        ),
    ]
