# Generated by Django 3.1 on 2022-06-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220618_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Блок команды',
                'verbose_name_plural': 'Блок команды',
            },
        ),
        migrations.CreateModel(
            name='TeamItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Элемент команды')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_team_member', to='home.teamblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент команды',
                'verbose_name_plural': 'Элементы команды',
            },
        ),
    ]
