# Generated by Django 3.1 on 2022-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_teamblockmodel_teamitemmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamitemmodel',
            options={'ordering': ['order'], 'verbose_name': 'Элемент команды', 'verbose_name_plural': 'Элементы команды'},
        ),
        migrations.AddField(
            model_name='teamitemmodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
