# Generated by Django 3.1 on 2022-06-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220618_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Верхний текст')),
                ('big_text', models.TextField(blank=True, null=True, verbose_name='Большой текст')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Нижний текст')),
            ],
            options={
                'verbose_name': 'Блок технологий',
                'verbose_name_plural': 'Блок технологий',
            },
        ),
        migrations.CreateModel(
            name='TechnologyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_technology', to='home.technologiesblockmodel', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
    ]
