# Generated by Django 3.1 on 2022-06-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_applicationmodel_contactsmodel_footermodel_linksmodel_locationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
