# Generated by Django 3.1 on 2022-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220619_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottomslide',
            options={'ordering': ['order'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order'], 'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='problempart',
            options={'ordering': ['order'], 'verbose_name': 'Часть проблемы', 'verbose_name_plural': 'Части проблемы'},
        ),
        migrations.AddField(
            model_name='bottomslide',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='problempart',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
