# Generated by Django 3.1 on 2022-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220620_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksmodel',
            options={'ordering': ['order'], 'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='linksmodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
