# Generated by Django 3.1 on 2022-06-20 17:29

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_colormodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AddField(
            model_name='colormodel',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Оставить настройки по умолчанию'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=app.fields.ColorField(default='#ffffff', max_length=10, verbose_name='Выбрать цвет'),
        ),
    ]
