# Generated by Django 3.1 on 2022-06-20 23:12

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220620_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='description_font_color',
            field=app.fields.ColorField(default='#4036ba', max_length=10, verbose_name='Выбрать цвет текста в блоке описания'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='func_list_color',
            field=app.fields.ColorField(default='#24d7ff', max_length=10, verbose_name='Выбрать цвет элементов списка'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=app.fields.ColorField(default='#4036ba', max_length=10, verbose_name='Выбрать цвет'),
        ),
    ]
