# Generated by Django 3.1 on 2022-06-26 23:42

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_colormodel_func_list_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='secondary_color',
            field=app.fields.ColorField(default='#24d7ff', max_length=10, verbose_name='Выбрать второй цвет'),
        ),
    ]
