# Generated by Django 3.1 on 2022-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_colormodel_secondary_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'ordering': ['order'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AddField(
            model_name='colormodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Применяется схема с наименьшим номером'),
        ),
    ]
